"""Upgrade to SQLAlchemy 2.0.16

Revision ID: 8d4cf7d3c9cb
Revises: fd22da67719f
Create Date: 2023-06-13 01:32:26.367350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4cf7d3c9cb'
down_revision = 'fd22da67719f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
