import datetime
import json
import os
from unittest.mock import patch

import pytest
from celery import Celery
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session, sessionmaker

import processor.classifiers as classifiers
from processor.database import projects_db
from processor.database.models import Base, ProjectHistory, Story

base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


@pytest.fixture(scope="session")
def celery_config():
    # Use in-memory broker and backend - No need to change broker_url env variable
    return {
        "broker_url": "memory://",
        "result_backend": "memory://",
        "task_always_eager": True,
    }


@pytest.fixture(scope="session")
def celery_includes():
    # Our tasks associated with our fetch -> queue -> classify -> post pipeline
    return ["processor.tasks.classification"]


@pytest.fixture(scope="session")
def celery_app(celery_config):
    # intialize test celery app, with memory broker and classification tasks
    app = Celery("test")
    app.config_from_object(celery_config)
    app.autodiscover_tasks(celery_includes)
    return app


# Fixtures
@pytest.fixture(scope="module")
def db_engine():
    # modify the column definitions to allow null values, will be helpful in initializing rows in our tables
    ProjectHistory.__table__.columns["latest_date_mc"].nullable = True
    ProjectHistory.__table__.columns["latest_date_nc"].nullable = True
    ProjectHistory.__table__.columns["latest_date_wm"].nullable = True

    Story.__table__.columns["model_score"].nullable = True
    Story.__table__.columns["model_1_score"].nullable = True
    Story.__table__.columns["model_2_score"].nullable = True
    Story.__table__.columns["processed_date"].nullable = True
    Story.__table__.columns["queued_date"].nullable = True
    Story.__table__.columns["posted_date"].nullable = True

    # create sqlite database
    engine = create_engine("sqlite:///:memory:")

    # create tables
    Base.metadata.create_all(engine)

    yield engine

    engine.dispose()


@pytest.fixture(scope="module")
def db_session_maker(db_engine):
    Session = sessionmaker(bind=db_engine)
    # mock the session maker
    with patch("processor.database.get_session_maker", return_value=Session):
        yield Session


@pytest.fixture(scope="module")
def mock_load_projects(db_session_maker):
    # create project_list with one sample project
    mock_project_list = [
        {
            "id": 1111,
            "title": "Test project",
            "language": "en",
            "start_date": "2023-01-08T16:03:00.000Z",
            "end_date": "2024-01-08T16:03:00.000Z",
            "search_terms": '(("climate change"))',
            "rss_url": None,
            "country": "US",
            "newscatcher_country": "US",
            "media_collections": [34412234, 38379429],
            "min_confidence": 0.75,
            "language_model": "stubbed model",
            "language_model_id": 1111,
        }
    ]

    # Add/get history for our mock_project_list
    with patch("processor.projects.load_project_list", return_value=mock_project_list):
        Session = db_session_maker
        with Session() as session:
            for project in mock_project_list:
                project_history = projects_db.get_history(session, project["id"])
                if project_history is None:
                    projects_db.add_history(session, project["id"])
        yield mock_project_list


@pytest.fixture(scope="module")
def mock_fetch_project_stories(db_session_maker, mock_load_projects):
    with patch("scripts.queue_newscatcher_stories.fetch_project_stories") as mock_fetch:
        stories = [
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/07/why-bidens-ban-on-drilling-in-the-alaska-national-wildlife-refuge-likely-wont-affect-gas-prices/",
                "source_publish_date": datetime.datetime(2023, 9, 7, 0, 0),
                "title": "Why Bidenâ\x80\x99s ban on drilling in the Alaska National Wildlife Refuge likely wonâ\x80\x99t affect gas prices",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/11/extreme-heat-fires-and-floods-threaten-europes-economy/",
                "source_publish_date": datetime.datetime(2023, 9, 11, 0, 0),
                "title": "Extreme heat, fires and floods threaten Europeâ\x80\x99s economy",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/11/the-origin-of-elon-musks-feud-with-bill-gates-according-to-musks-new-biography/",
                "source_publish_date": datetime.datetime(2023, 9, 11, 0, 0),
                "title": "The origin of Elon Muskâ\x80\x99s feud with Bill Gates, according to Muskâ\x80\x99s new biography",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/12/bp-ceo-resigns-after-probe-reveals-undisclosed-relationships-with-colleagues/",
                "source_publish_date": datetime.datetime(2023, 9, 12, 0, 0),
                "title": "BP CEO resigns after probe reveals undisclosed relationships with colleagues",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/19/insurance-premiums-could-surge-in-these-american-cities-because-of-climate-disasters-new-data-shows/",
                "source_publish_date": datetime.datetime(2023, 9, 19, 0, 0),
                "title": "Insurance premiums could surge in these American cities because of climate disasters, new data shows",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/20/the-uk-may-delay-its-switch-to-electric-cars-automakers-slam-confusion/",
                "source_publish_date": datetime.datetime(2023, 9, 20, 0, 0),
                "title": "The UK is delaying the switch to electric cars. Automakers are furious",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/21/rupert-murdoch-steps-down-as-fox-and-news-corp-chairman/",
                "source_publish_date": datetime.datetime(2023, 9, 21, 0, 0),
                "title": "Rupert Murdoch steps down as Fox and News Corp. chairman, sending shockwaves through media and politics",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/21/rupert-murdoch-steps-down-as-fox-chairman/",
                "source_publish_date": datetime.datetime(2023, 9, 21, 0, 0),
                "title": "Rupert Murdoch steps down as Fox and News Corp. chairman, sending shockwaves through media and politics",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/22/california-paves-way-for-more-insurance-coverage-in-disaster-prone-areas/",
                "source_publish_date": datetime.datetime(2023, 9, 22, 0, 0),
                "title": "California paves way for more insurance coverage in disaster-prone areas",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/27/biden-teases-forthcoming-executive-order-on-ai/",
                "source_publish_date": datetime.datetime(2023, 9, 27, 0, 0),
                "title": "Biden teases forthcoming executive order on AI",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/09/27/britain-approves-huge-controversial-oil-and-gas-field-in-the-north-sea/",
                "source_publish_date": datetime.datetime(2023, 9, 27, 0, 0),
                "title": "Britain approves huge, controversial oil and gas field in the North Sea",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/10/03/starbucks-scientists-are-developing-climate-proof-coffee/",
                "source_publish_date": datetime.datetime(2023, 10, 3, 0, 0),
                "title": "Coffee is in danger. Starbucks is working on solutions",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/10/10/the-climate-crisis-is-coming-for-your-hoppy-beer/",
                "source_publish_date": datetime.datetime(2023, 10, 10, 0, 0),
                "title": "The climate crisis is coming for your hoppy beer",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/10/17/why-fed-officials-arent-addressing-the-israel-hamas-war-the-way-they-did-with-ukraine/",
                "source_publish_date": datetime.datetime(2023, 10, 17, 0, 0),
                "title": "Why Fed officials arenâ\x80\x99t addressing the Israel-Hamas war the way they did with Ukraine",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/10/19/fed-chair-powell-to-deliver-remarks-during-uncertain-moment-for-the-us-economy/",
                "source_publish_date": datetime.datetime(2023, 10, 19, 0, 0),
                "title": "Fed Chair Powell hints that soaring bond yields could mean end of rate hikes",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/10/24/unstoppable-energy-transition-means-demand-for-oil-gas-and-coal-set-to-peak-by-2030/",
                "source_publish_date": datetime.datetime(2023, 10, 24, 0, 0),
                "title": "â\x80\x98Unstoppableâ\x80\x99 energy transition means demand for oil, gas, and coal set to peak by 2030",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/10/26/divorce-is-not-an-option-for-us-and-china-newsom-says-after-xi-meeting/",
                "source_publish_date": datetime.datetime(2023, 10, 26, 0, 0),
                "title": "â\x80\x98Divorce is not an optionâ\x80\x99 for US and China, Newsom says after Xi meeting",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/10/30/janet-yellen-to-deliver-major-speech-detailing-us-economic-strategy-toward-indo-pacific/",
                "source_publish_date": datetime.datetime(2023, 10, 30, 0, 0),
                "title": "Janet Yellen to deliver major speech detailing US economic strategy toward Indo-Pacific",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/11/02/six-flags-and-cedar-fair-are-merging/",
                "source_publish_date": datetime.datetime(2023, 11, 2, 0, 0),
                "title": "Six Flags and Cedar Fair are merging",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/11/07/climate-change-is-impacting-the-home-insurance-industry-and-damaging-the-housing-market/",
                "source_publish_date": datetime.datetime(2023, 11, 7, 0, 0),
                "title": "Climate change is impacting the home insurance industry and damaging the housing market",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/11/19/bloodbath-extreme-weather-and-falling-demand-are-pushing-wineries-into-the-red/",
                "source_publish_date": datetime.datetime(2023, 11, 19, 0, 0),
                "title": "Extreme weather and falling demand are pushing wineries into the red",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/11/26/how-ai-could-power-the-climate-breakthrough-the-world-needs/",
                "source_publish_date": datetime.datetime(2023, 11, 26, 0, 0),
                "title": "How AI could power the climate breakthrough the world needs",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/11/28/who-can-afford-to-go-green-hard-pressed-consumers-are-pushing-back/",
                "source_publish_date": datetime.datetime(2023, 11, 28, 0, 0),
                "title": "Who can afford to go green? Hard-pressed consumers are pushing back",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/11/29/jamie-dimon-says-to-be-prepared-for-recession/",
                "source_publish_date": datetime.datetime(2023, 11, 29, 0, 0),
                "title": "Jamie Dimon says to be prepared for recession",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/11/30/climate-change-is-costing-the-us-150-billion-a-year-heres-what-that-looks-like/",
                "source_publish_date": datetime.datetime(2023, 11, 30, 0, 0),
                "title": "Climate change is costing the US $150 billion a year. Hereâ\x80\x99s what that looks like",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/11/30/senate-committee-investigating-floridas-state-backed-home-insurance-company-as-private-insurers-flee/",
                "source_publish_date": datetime.datetime(2023, 11, 30, 0, 0),
                "title": "Senate committee investigating Floridaâ\x80\x99s state-backed home insurance company as private insurers flee",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/12/03/clean-energy-stocks-have-fallen-out-of-favor-they-face-more-challenges-ahead/",
                "source_publish_date": datetime.datetime(2023, 12, 3, 0, 0),
                "title": "Clean energy stocks have fallen out of favor. They face more challenges ahead",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/12/05/how-old-fishing-nets-could-be-part-of-the-climate-crisis-solution/",
                "source_publish_date": datetime.datetime(2023, 12, 5, 0, 0),
                "title": "How old fishing nets could be part of the climate crisis solution",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/12/11/elon-musks-x-is-encouraging-users-to-follow-conspiracy-theorist-alex-jones-after-reinstating-his-account/",
                "source_publish_date": datetime.datetime(2023, 12, 11, 0, 0),
                "title": "Elon Muskâ\x80\x99s X is encouraging users to follow conspiracy theorist Alex Jones after reinstating his account",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/12/14/ai-is-a-danger-to-the-financial-system-regulators-warn-for-the-first-time/",
                "source_publish_date": datetime.datetime(2023, 12, 14, 0, 0),
                "title": "AI is a danger to the financial system, regulators warn for the first time",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-business-consumer/2023/12/19/the-united-states-is-producing-more-oil-than-any-country-in-history/",
                "source_publish_date": datetime.datetime(2023, 12, 19, 0, 0),
                "title": "The United States is producing more oil than any country in history",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/money/cnn-social-media-technology/2023/02/09/elon-musk-pledged-transparency-at-twitter-but-hes-walling-off-researchers/",
                "source_publish_date": datetime.datetime(2023, 2, 9, 0, 0),
                "title": "Elon Musk pledged transparency at Twitter. But he's walling off researchers",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/08/lightning-in-the-cataclysmic-tonga-volcano-eruption-shattered-all-records/",
                "source_publish_date": datetime.datetime(2023, 1, 8, 0, 0),
                "title": "Lightning in the 'cataclysmic' Tonga volcano eruption shattered 'all records'",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/10/inside-plans-for-copenhagens-divisive-artificial-storm-absorbing-peninsula/",
                "source_publish_date": datetime.datetime(2023, 1, 10, 0, 0),
                "title": "Inside plans for Copenhagen's divisive artificial storm-absorbing peninsula",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/11/5-things-to-know-for-jan-11-storms-ukraine-us-military-airline-complaints-eggs-2/",
                "source_publish_date": datetime.datetime(2023, 1, 11, 0, 0),
                "title": "5 things to know for Jan. 11: Storms, Ukraine, US military, Airline complaints, Eggs",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/11/brutality-of-prehistoric-life-revealed-by-europes-bog-bodies/",
                "source_publish_date": datetime.datetime(2023, 1, 11, 0, 0),
                "title": "Brutality of prehistoric life revealed by Europe's bog bodies",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/12/exxon-accurately-predicted-global-warming-from-1970s-but-continued-to-cast-doubt-on-climate-science-new-report-finds/",
                "source_publish_date": datetime.datetime(2023, 1, 12, 0, 0),
                "title": "Exxon accurately predicted global warming from 1970s - but continued to cast doubt on climate science, new report finds",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/13/inside-5-days-of-a-white-house-determined-to-maintain-business-as-usual/",
                "source_publish_date": datetime.datetime(2023, 1, 13, 0, 0),
                "title": "Inside 5 days of a White House determined to maintain business as usual",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/13/why-an-arab-nation-has-opted-to-teach-the-holocaust-in-its-schools/",
                "source_publish_date": datetime.datetime(2023, 1, 13, 0, 0),
                "title": "Why an Arab nation has opted to teach the Holocaust in its schools",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/14/how-to-watch-the-71st-miss-universe-competition-2/",
                "source_publish_date": datetime.datetime(2023, 1, 14, 0, 0),
                "title": "How to watch the 71st Miss Universe competition",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/14/thousands-protest-in-germany-against-coal-mine-expansion/",
                "source_publish_date": datetime.datetime(2023, 1, 14, 0, 0),
                "title": "Thousands protest in Germany against coal mine expansion",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/15/russias-war-in-ukraine-sparked-a-historic-food-crisis-its-not-over/",
                "source_publish_date": datetime.datetime(2023, 1, 15, 0, 0),
                "title": "Russia's war in Ukraine sparked a historic food crisis. It's not over",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/15/were-still-on-the-bunny-slopes-as-2023-kicks-off-is-canadas-climate-change-plan-aggressive-enough-2/",
                "source_publish_date": datetime.datetime(2023, 1, 15, 0, 0),
                "title": "We're still on the bunny slopes': As 2023 kicks off, is Canada's climate change plan aggressive enough?",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/18/chinas-population-is-shrinking-the-impact-will-be-felt-around-the-world/",
                "source_publish_date": datetime.datetime(2023, 1, 18, 0, 0),
                "title": "China's population is shrinking. The impact will be felt around the world",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/18/new-zealands-jacinda-ardern-an-icon-to-many-to-step-down/",
                "source_publish_date": datetime.datetime(2023, 1, 18, 0, 0),
                "title": "New Zealand's Jacinda Ardern, an icon to many, to step down",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/18/the-federal-reserve-is-testing-how-climate-change-could-hurt-big-banks/",
                "source_publish_date": datetime.datetime(2023, 1, 18, 0, 0),
                "title": "The Federal Reserve is testing how climate change could hurt big banks",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/20/this-small-airplane-could-hold-the-key-to-zero-carbon-flying/",
                "source_publish_date": datetime.datetime(2023, 1, 20, 0, 0),
                "title": "This small airplane could hold the key to zero-carbon flying",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/20/what-we-learned-at-davos-the-economy-is-a-mess-but-theres-still-hope/",
                "source_publish_date": datetime.datetime(2023, 1, 20, 0, 0),
                "title": "What we learned at Davos: The economy is a mess, but there's still hope",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/23/chinas-northernmost-city-just-saw-its-coldest-day-ever/",
                "source_publish_date": datetime.datetime(2023, 1, 23, 0, 0),
                "title": "China's northernmost city just saw its coldest day ever",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/24/the-doomsday-clock-reveals-how-close-we-are-to-total-annihilation/",
                "source_publish_date": datetime.datetime(2023, 1, 24, 0, 0),
                "title": "The Doomsday Clock reveals how close we are to total annihilation",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/25/cat-size-primate-relatives-lived-in-the-arctic-52-million-years-ago/",
                "source_publish_date": datetime.datetime(2023, 1, 25, 0, 0),
                "title": "Fossils reveal the mysterious primate relatives that lived in the ancient Arctic",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/27/a-ginormous-can-of-worms-how-a-fight-over-snow-crabs-could-lead-to-a-win-for-oil-drilling-access/",
                "source_publish_date": datetime.datetime(2023, 1, 27, 0, 0),
                "title": "A ginormous can of worms': How a fight over snow crabs could lead to a win for oil drilling access",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/27/gop-led-states-sue-biden-administration-to-block-esg-investment-rule/",
                "source_publish_date": datetime.datetime(2023, 1, 27, 0, 0),
                "title": "GOP-led states sue Biden administration to block ESG investment rule",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/30/new-zealands-biggest-city-braces-for-more-heavy-rains-after-deadly-floods/",
                "source_publish_date": datetime.datetime(2023, 1, 30, 0, 0),
                "title": "New Zealand's biggest city braces for more heavy rains after deadly floods",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/30/who-says-covid-19-remains-a-global-health-emergency-but-pandemic-is-at-a-transition-point/",
                "source_publish_date": datetime.datetime(2023, 1, 30, 0, 0),
                "title": "WHO says Covid-19 remains a global health emergency, but pandemic is at a 'transition point'",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/31/california-releases-its-own-plan-for-colorado-river-cuts/",
                "source_publish_date": datetime.datetime(2023, 1, 31, 0, 0),
                "title": "California releases its own plan for Colorado River cuts",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/01/31/degradation-of-amazon-rainforest-by-humans-is-causing-as-many-carbon-emissions-as-deforestation-study/",
                "source_publish_date": datetime.datetime(2023, 1, 31, 0, 0),
                "title": "Degradation of Amazon rainforest by humans is causing as many carbon emissions as deforestation: study",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/01/india-to-raise-spending-on-job-creation-ahead-of-election/",
                "source_publish_date": datetime.datetime(2023, 2, 1, 0, 0),
                "title": "India to raise spending on job creation ahead of election",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/02/greenpeace-activists-scale-shell-oil-platform-in-the-atlantic-ocean-as-company-announces-record-profits/",
                "source_publish_date": datetime.datetime(2023, 2, 2, 0, 0),
                "title": "Greenpeace activists scale Shell oil platform in the Atlantic Ocean as company announces record profits",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/09/opal-lee-the-grandmother-of-juneteenth-becomes-second-black-american-to-have-portrait-hung-in-texas-statehouse/",
                "source_publish_date": datetime.datetime(2023, 2, 9, 0, 0),
                "title": "Opal Lee, the 'grandmother of Juneteenth,' becomes second Black American to have portrait hung in Texas statehouse",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/10/a-subsidy-arms-race-is-kicking-off-between-europe-and-america/",
                "source_publish_date": datetime.datetime(2023, 2, 10, 0, 0),
                "title": "A subsidy arms race is kicking off between Europe and America",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/10/democracy-on-the-agenda-as-biden-meets-brazils-lula-at-the-white-house/",
                "source_publish_date": datetime.datetime(2023, 2, 10, 0, 0),
                "title": "Democracy on the agenda as Biden meets Brazil's Lula at the White House",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/10/exceptional-warming-january-temperatures-2-2-degrees-higher-than-average-in-europe/",
                "source_publish_date": datetime.datetime(2023, 2, 10, 0, 0),
                "title": "Exceptional' warming: January temperatures 2.2 degrees higher than average in Europe",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/10/long-term-exposure-to-air-pollution-may-raise-risk-of-depression-later-in-life-study-says/",
                "source_publish_date": datetime.datetime(2023, 2, 10, 0, 0),
                "title": "Long-term exposure to air pollution may raise risk of depression later in life, study says",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/10/lula-says-brazil-is-no-more-divided-than-the-us-as-he-meets-biden/",
                "source_publish_date": datetime.datetime(2023, 2, 10, 0, 0),
                "title": "Lula says Brazil is no more divided than the US as he meets Biden",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/12/launching-balloons-high-into-the-atmosphere-to-unload-sun-reflecting-particles-big-climate-solution-or-colossal-disaster/",
                "source_publish_date": datetime.datetime(2023, 2, 12, 0, 0),
                "title": "Supporters of a controversial climate solution say it could be key. Critics believe it is the path to catastrophe",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/13/flowers-and-trees-blooming-up-to-3-weeks-earlier-than-normal-in-the-eastern-us/",
                "source_publish_date": datetime.datetime(2023, 2, 13, 0, 0),
                "title": "Flowers and trees blooming up to 3 weeks earlier than normal in the Eastern US",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/15/new-zealands-stunning-landscape-was-carved-from-water-now-too-much-is-risking-lives/",
                "source_publish_date": datetime.datetime(2023, 2, 15, 0, 0),
                "title": "Water carved New Zealand's stunning landscape. Now too much is risking lives",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/21/margarita-buzzkill-how-the-climate-crisis-is-threatening-tequila/",
                "source_publish_date": datetime.datetime(2023, 2, 21, 0, 0),
                "title": "Why the climate crisis may be coming for your margarita next",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/21/the-beginning-of-the-end-scientists-sound-the-alarm-as-antarctic-sea-ice-hits-record-low-for-second-year-running/",
                "source_publish_date": datetime.datetime(2023, 2, 21, 0, 0),
                "title": "Antarctic sea ice hit record lows again. Scientists wonder if it's 'the beginning of the end'",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/21/who-is-michael-regan-the-head-of-the-environmental-protection-agency/",
                "source_publish_date": datetime.datetime(2023, 2, 21, 0, 0),
                "title": "Who is Michael Regan, the head of the Environmental Protection Agency?",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/24/dry-canals-low-rivers-and-shrunken-lakes-europe-braces-for-severe-drought-amid-winter-heatwave/",
                "source_publish_date": datetime.datetime(2023, 2, 24, 0, 0),
                "title": "Dry canals, low rivers and shrunken lakes: Europe braces for severe drought amid winter heatwave",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/26/a-time-bomb-indias-sinking-holy-town-faces-grim-future/",
                "source_publish_date": datetime.datetime(2023, 2, 26, 0, 0),
                "title": "‘A time bomb’: India’s sinking holy town faces grim future",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/26/us-energy-department-assesses-covid-19-likely-resulted-from-lab-leak-furthering-us-intel-divide-over-virus-origin-2/",
                "source_publish_date": datetime.datetime(2023, 2, 26, 0, 0),
                "title": "US ambassador calls on China to be 'more honest' about Covid origins",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/27/brexit-deal-on-northern-ireland-nears-as-king-charles-welcomes-eu-chief-von-der-leyen-at-windsor/",
                "source_publish_date": datetime.datetime(2023, 2, 27, 0, 0),
                "title": "EU and UK strike new deal over post-Brexit trade rules in Northern Ireland",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/27/corporate-greenwashing-can-satisfy-stakeholders-without-environmental-results-study-finds/",
                "source_publish_date": datetime.datetime(2023, 2, 27, 0, 0),
                "title": "Corporate 'greenwashing' can satisfy stakeholders without environmental results, study finds",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/27/hurricane-damage-will-increase-in-surprising-new-places-in-the-coming-decades-see-where-its-trending-higher/",
                "source_publish_date": datetime.datetime(2023, 2, 27, 0, 0),
                "title": "Hurricane damage will increase in surprising new places in the coming decades. See where it's trending higher",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/27/us-ambassador-calls-on-china-to-be-more-honest-about-covid-origins/",
                "source_publish_date": datetime.datetime(2023, 2, 27, 0, 0),
                "title": "US ambassador calls on China to be 'more honest' about Covid origins",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/02/28/a-little-scary-iditarod-begins-with-smallest-field-ever-2/",
                "source_publish_date": datetime.datetime(2023, 2, 28, 0, 0),
                "title": 'A little scary:" Iditarod begins with smallest field ever',
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/01/dcs-cherry-blossoms-coming-early-due-to-confusing-weather/",
                "source_publish_date": datetime.datetime(2023, 3, 1, 0, 0),
                "title": "DC's cherry blossoms coming early due to confusing weather",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/01/india-urges-g-20-ministers-to-look-beyond-east-west-crisis/",
                "source_publish_date": datetime.datetime(2023, 3, 1, 0, 0),
                "title": "India urges G-20 ministers to look beyond East-West crisis",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/01/john-roberts-takes-center-stage-in-the-battle-over-student-loan-forgiveness/",
                "source_publish_date": datetime.datetime(2023, 3, 1, 0, 0),
                "title": "John Roberts takes center stage in the battle over student loan forgiveness",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/02/big-money-coming-to-colorado-to-fight-climate-change-and-create-jobs/",
                "source_publish_date": datetime.datetime(2023, 3, 2, 0, 0),
                "title": "Big money coming to Colorado to fight climate change and create jobs",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/03/doj-ramps-up-its-allegations-that-texas-is-judge-shopping-in-cases-against-biden/",
                "source_publish_date": datetime.datetime(2023, 3, 3, 0, 0),
                "title": "DOJ ramps up its allegations that Texas is 'judge-shopping' in cases against Biden",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/03/the-ukraine-war-sends-message-to-aggressors-everywhere-says-blinken-at-quad-meeting/",
                "source_publish_date": datetime.datetime(2023, 3, 3, 0, 0),
                "title": "The Ukraine war sends message to 'aggressors everywhere,' says Blinken at Quad meeting",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/04/countries-agree-historic-oceans-treaty-to-protect-the-high-seas/",
                "source_publish_date": datetime.datetime(2023, 3, 4, 0, 0),
                "title": "Countries agree historic oceans treaty to protect the high seas",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/07/europe-is-trying-to-ditch-planes-for-trains-heres-how-thats-going/",
                "source_publish_date": datetime.datetime(2023, 3, 7, 0, 0),
                "title": "Europe is trying to ditch planes for trains. Here's how that's going",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/07/threat-of-rising-seas-to-asian-megacities-could-be-way-worse-than-we-thought-study-warns/",
                "source_publish_date": datetime.datetime(2023, 3, 7, 0, 0),
                "title": "Threat of rising seas to Asian megacities could be way worse than we thought, study warns",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/09/biden-to-make-first-visit-to-canada-as-president-later-this-month/",
                "source_publish_date": datetime.datetime(2023, 3, 9, 0, 0),
                "title": "Biden to make first visit to Canada as president later this month",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/09/what-is-an-atmospheric-river/",
                "source_publish_date": datetime.datetime(2023, 3, 9, 0, 0),
                "title": "What is an atmospheric river?",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/10/outgoing-president-of-micronesia-accuses-china-of-bribery-threats-and-political-warfare/",
                "source_publish_date": datetime.datetime(2023, 3, 10, 0, 0),
                "title": "Outgoing president of Micronesia accuses China of bribery, threats and 'political warfare'",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/10/scientists-find-a-way-to-suck-up-carbon-pollution-turn-it-into-baking-soda-and-store-it-in-the-oceans/",
                "source_publish_date": datetime.datetime(2023, 3, 10, 0, 0),
                "title": "Scientists find a way to suck up carbon pollution, turn it into baking soda and store it in the oceans",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/10/white-house-to-approve-major-oil-alaska-oil-drilling-project-willow/",
                "source_publish_date": datetime.datetime(2023, 3, 10, 0, 0),
                "title": "Biden administration to approve major Alaska oil drilling project Willow",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/13/biden-administration-will-approve-willow-oil-project-in-alaska-with-three-drilling-pads-instead-of-two/",
                "source_publish_date": datetime.datetime(2023, 3, 13, 0, 0),
                "title": "Biden administration approves controversial Willow oil project in Alaska, which has galvanized online activism",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/15/endless-brutal-heat-argentinas-late-season-heatwave-has-no-similarities-in-history/",
                "source_publish_date": datetime.datetime(2023, 3, 15, 0, 0),
                "title": "Endless, brutal heat': Argentina's late-season heatwave has 'no similarities in history'",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/16/cyclone-freddy-survivors-dig-with-bare-hands-for-victims-as-death-toll-reaches-326/",
                "source_publish_date": datetime.datetime(2023, 3, 16, 0, 0),
                "title": "Cyclone Freddy survivors dig with bare hands for victims as death toll reaches 326",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/18/haley-ramaswamy-among-those-taking-on-woke-ideology-in-sc/",
                "source_publish_date": datetime.datetime(2023, 3, 18, 0, 0),
                "title": "Haley, Ramaswamy among those taking on 'woke ideology' in SC",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/20/biden-issues-his-first-veto-on-retirement-investment-resolution/",
                "source_publish_date": datetime.datetime(2023, 3, 20, 0, 0),
                "title": "Biden issues his first veto on retirement investment resolution",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/21/biden-to-designate-national-monuments-in-nevada-texas/",
                "source_publish_date": datetime.datetime(2023, 3, 21, 0, 0),
                "title": "Biden to designate national monuments in Nevada, Texas",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
            {
                "url": "https://abc17news.com/news/2023/03/22/global-water-crisis-could-spiral-out-of-control-due-to-overconsumption-and-climate-change-un-report-warns/",
                "source_publish_date": datetime.datetime(2023, 3, 22, 0, 0),
                "title": "Global water crisis could 'spiral out of control' due to overconsumption and climate change, UN report warns",
                "source": "newscatcher",
                "project_id": 1111,
                "language": "en",
                "authors": [],
                "media_name": "abc17news.com",
                "media_url": "http://abc17news.com",
            },
        ]
        mock_fetch.return_value = stories
        yield mock_fetch


@pytest.fixture(scope="module")
def mock_model_list():
    # load the mock_model_list from  our test language_models.json file
    with open(
        os.path.join(base_dir, "test", "fixtures", "language_models.json"), "r"
    ) as f:
        fake_model_list = json.load(f)
    with patch("processor.classifiers.get_model_list", return_value=fake_model_list):
        # now calling get_model_list() will return our fake model list
        model_list = classifiers.get_model_list()
        mock_model_list.return_value = model_list
        assert len(model_list) == 1
        assert model_list[0]["id"] == "1111"
        yield


def patch_update_stories_above_threshold(session: Session) -> None:
    # select stories with confidence >= 0.75 and set above_threshold to True
    # update_stories_above_threshold doesn't run properly with our in-session db so we are replicating the behavior
    session.execute(
        text(
            """
            UPDATE stories
            SET above_threshold = True
            WHERE model_score >= 0.75
            """
        )
    )
    session.commit()
